// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5TcomdHu2J-Cwjw2oBJYIUzhSE5nPIv4',
    appId: '1:612840455198:web:48f3881fc3c8c47c5a420f',
    messagingSenderId: '612840455198',
    projectId: 'flutterproject-f02e6',
    authDomain: 'flutterproject-f02e6.firebaseapp.com',
    storageBucket: 'flutterproject-f02e6.firebasestorage.app',
    measurementId: 'G-1XE7GNJHX2',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC5TcomdHu2J-Cwjw2oBJYIUzhSE5nPIv4', // Use your Web API key
    appId: '1:612840455198:web:48f3881fc3c8c47c5a420f', // Use Web App ID
    messagingSenderId: '612840455198',
    projectId: 'flutterproject-f02e6',
    authDomain: 'flutterproject-f02e6.firebaseapp.com',
    storageBucket: 'flutterproject-f02e6.firebasestorage.app',
    measurementId: 'G-1XE7GNJHX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhDcMnsd-ou3M7vT8guHijgp8EwBGqdOQ',
    appId: '1:612840455198:android:955d3b92ff0fead35a420f',
    messagingSenderId: '612840455198',
    projectId: 'flutterproject-f02e6',
    storageBucket: 'flutterproject-f02e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf2AGtVMoeLB9dos0HJuWD_XvwfQLKCgs',
    appId: '1:612840455198:ios:dd1fc7ef6479299f5a420f',
    messagingSenderId: '612840455198',
    projectId: 'flutterproject-f02e6',
    storageBucket: 'flutterproject-f02e6.firebasestorage.app',
    iosBundleId: 'com.example.multitaskLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf2AGtVMoeLB9dos0HJuWD_XvwfQLKCgs',
    appId: '1:612840455198:ios:dd1fc7ef6479299f5a420f',
    messagingSenderId: '612840455198',
    projectId: 'flutterproject-f02e6',
    storageBucket: 'flutterproject-f02e6.firebasestorage.app',
    iosBundleId: 'com.example.multitaskLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5TcomdHu2J-Cwjw2oBJYIUzhSE5nPIv4',
    appId: '1:612840455198:web:36e5c501b8aa08695a420f',
    messagingSenderId: '612840455198',
    projectId: 'flutterproject-f02e6',
    authDomain: 'flutterproject-f02e6.firebaseapp.com',
    storageBucket: 'flutterproject-f02e6.firebasestorage.app',
    measurementId: 'G-XBJSQ4YBME',
  );
}
